#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA_PATH="$ROOT_DIR/schema/v1/dataset.schema.json"
OUTPUT_PATH="$ROOT_DIR/app/src/lib/types/dataset.d.ts"
BANNER=$'/* eslint-disable */\n/**\n * This file is auto-generated by scripts/generate-types.sh.\n * Do not edit directly.\n */'

cd "$ROOT_DIR/app"
./node_modules/.bin/json2ts --input "$SCHEMA_PATH" --output "$OUTPUT_PATH" --bannerComment "$BANNER"
