#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$ROOT_DIR/app/src/lib/types/dataset.d.ts"
TMP_DIR="$(mktemp -d)"
TMP_OUT="$TMP_DIR/dataset.d.ts"
BANNER=$'/* eslint-disable */\n/**\n * This file is auto-generated by scripts/generate-types.sh.\n * Do not edit directly.\n */'

cd "$ROOT_DIR/app"
./node_modules/.bin/json2ts --input "$ROOT_DIR/schema/v1/dataset.schema.json" --output "$TMP_OUT" --bannerComment "$BANNER"

diff -u "$TARGET" "$TMP_OUT"
